var annotated_dup =
[
    [ "config_master_i2c", "structconfig__master__i2c.html", null ],
    [ "config_scroll_ssd1306", "structconfig__scroll__ssd1306.html", null ],
    [ "config_slave_i2c", "structconfig__slave__i2c.html", null ],
    [ "config_SSD1306", "structconfig___s_s_d1306.html", null ],
    [ "Framebuffer", "class_framebuffer.html", null ],
    [ "hw_I2C_master", "classhw___i2_c__master.html", "classhw___i2_c__master" ],
    [ "hw_I2C_slave", "classhw___i2_c__slave.html", "classhw___i2_c__slave" ],
    [ "i2c_xfer_result", "structi2c__xfer__result.html", null ],
    [ "MSGEQ7", "class_m_s_g_e_q7.html", null ],
    [ "Probe", "class_probe.html", "class_probe" ],
    [ "RotaryEncoder", "class_rotary_encoder.html", null ],
    [ "slave_memory", "structslave__memory.html", null ],
    [ "SSD1306", "class_s_s_d1306.html", "class_s_s_d1306" ],
    [ "struct_render_area", "structstruct__render__area.html", null ],
    [ "StructFramebufferText", "struct_struct_framebuffer_text.html", null ],
    [ "StructSwitchButtonConfig", "struct_struct_switch_button_config.html", null ],
    [ "StructWidgetConfig", "struct_struct_widget_config.html", null ],
    [ "SwitchButton", "class_switch_button.html", "class_switch_button" ],
    [ "SwitchButtonWithIRQ", "class_switch_button_with_i_r_q.html", "class_switch_button_with_i_r_q" ],
    [ "Test_Manager", "class_test___manager.html", "class_test___manager" ],
    [ "TestCursorWidgetWithIncrementalValue", "class_test_cursor_widget_with_incremental_value.html", "class_test_cursor_widget_with_incremental_value" ],
    [ "TestIncrementalValue", "class_test_incremental_value.html", "class_test_incremental_value" ],
    [ "TestObjectManagerWidget", "class_test_object_manager_widget.html", "class_test_object_manager_widget" ],
    [ "UIControlledIncrementalValue", "class_u_i_controlled_incremental_value.html", "class_u_i_controlled_incremental_value" ],
    [ "UIController", "class_u_i_controller.html", "class_u_i_controller" ],
    [ "UIDisplayDevice", "class_u_i_display_device.html", "class_u_i_display_device" ],
    [ "UIModelObject", "class_u_i_model_object.html", "class_u_i_model_object" ],
    [ "UIObjectManager", "class_u_i_object_manager.html", "class_u_i_object_manager" ],
    [ "UIWidget", "class_u_i_widget.html", "class_u_i_widget" ]
];